#!/usr/bin/env bash

REPO_DIR=$(cd $(dirname $0) && pwd)

##
 # back up files before creating links
 ##
echo "backing up old files to .old"

declare -a FILES=(
  .aliases
  .bashrc
  .colors
  .functions
  .gitconfig
  .gitignore_global
  .lein/profiles.clj
  .vimrc
)

for file in ${FILES[@]}; do
  if [ -f ~/${file} -a ! -h ~/${file} ]; then
    echo "backing up ${file}..."
    mv ~/${file} ~/${file}.old
  fi
done

##
 # create links
 ##
echo "linking to new files"

# only create directory link if not present (creates circular link otherwise)
if ! [ -d ~/.vim ]; then
  ln -sf ${REPO_DIR}/.vim ~/.vim
fi

for file in ${FILES[@]}; do
  ln -sf ${REPO_DIR}/${file} ~/${file}
done

##
 # warn to set up bash_profile
 ##
if ! [ -f ~/.bash_profile ]; then
  echo "Set up your .bash_profile..."
  cp ./.bash_profile ~
fi
