#!/usr/bin/env bash

REPO_DIR=$(cd $(dirname $0) && pwd)

##
 # create links
 ##
# only create this link if it doesn't exist, creates circular link otherwise
if ! [ -d ~/.vim ]; then
  ln -sf ${REPO_DIR}/.vim ~/.vim
fi

echo "backing up old files to .old"
mv ~/.vimrc ~/.vimrc.old
mv ~/.aliaes ~/.aliases.old
mv ~/.bashrc ~/.bashrc.old
mv ~/.functions ~/.functions.old

echo "linking to new files"
ln -sf ${REPO_DIR}/.vim/.vimrc ~/.vimrc
ln -sf ${REPO_DIR}/.aliases ~/.aliases
ln -sf ${REPO_DIR}/.bashrc ~/.bashrc
ln -sf ${REPO_DIR}/.functions ~/.functions

if ! [ -f ~/.bash_profile ]; then
  echo "Set up your .bash_profile..."
  cp ./.bash_profile ~
fi
