#!/usr/bin/env bash

set -eu

WORKING_DIR=$(cd $(dirname $0) && pwd)

# install python tools before packages
brew install openssl pipx
make poetry

declare -a PACKAGES=(
  black
  cookiecutter
  flake8
  httpie
  httpie-jwt-auth
  python-language-server[all]
  rst2html5
  virtualenv
)

# install pipx utilities
for package in ${PACKAGES[@]}; do
  if pipx uninstall $package; then
    echo "Package '$package' not installed"
  fi
  pipx install $package --include-deps
done

echo "Linking rst2html5 for atom.io"
ln -sf /usr/local/bin/rst2html5 /usr/local/bin/rst2html
