#!/usr/bin/env bash

set -eu

WORKING_DIR=$(cd $(dirname $0) && pwd)

# install python tools before packages
brew install openssl

# install astral's uv for python stuff
curl -LsSf https://astral.sh/uv/install.sh | sh
uv python install 3.12
uv python install 3.11
uv python install 3.10