#!/usr/bin/env bash

set -eu

get_plugin_dir_name() {
  local dir_name=${1##*/} # get repo name
  dir_name=${dir_name%.*} # remove .git
  echo $dir_name
}

declare -a PLUGINS=(
  "scrooloose/nerdtree"
  "Xuyuanp/nerdtree-git-plugin"
  "plasticboy/vim-markdown"
  "tpope/vim-fireplace"
  "rust-lang/rust.vim"
  "fatih/vim-go"
  "rodjek/vim-puppet"
  "w0rp/ale"
)

##
 # check if plugins are installed by seeing if a .git dir is in the
 # corresponding directory of the plugin; if not clone.
 ##
BUNDLE_DIR=.vim/bundle

for plugin in ${PLUGINS[@]}; do
  DIR_NAME=$BUNDLE_DIR/$(get_plugin_dir_name $plugin)

  if [ ! -d $DIR_NAME/.git ]; then
    git clone https://github.com/$plugin $DIR_NAME
  else
    echo "$plugin seems to be installed; rm -rf $DIR_NAME to re-install"
  fi
done
