#!/usr/bin/env bash

get_plugin_dir_name() {
  local dir_name=${1##*/} # get repo name
  dir_name=${dir_name%.*} # remove .git
  echo $dir_name
}

# set up my destination directory and the plugins
bundle_dir=./.vim/bundle

declare -a plugins=(
  "scrooloose/nerdtree.git"
  "Xuyuanp/nerdtree-git-plugin.git"
  # "jistr/vim-nerdtree-tabs"
)

##
 # check if plugins are installed by seeing if a .git dir is in the
 # corresponding directory of the plugin; if not clone.
 ##
for plugin in "${plugins[@]}"
do
  dir_name=$bundle_dir/$(get_plugin_dir_name $plugin)

  if [ ! -d $dir_name/.git ]
  then
    git clone git@github.com:$plugin $dir_name
  else
    echo "$plugin seems to be installed; rm -rf $dir_name to re-install"
  fi
done
